# OMGZombies a plugin by DiOne
# Version 1.1

#Set the reward for each kill
Reward: 2

#Set the frequency in seconds zombies' spawn
Frequency: 5

#Enable or disable the fly
AllowFly: true

#Enable or disable the royals presence
Royals: true
